version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DJANGO_DATABASE_NAME}
      - POSTGRES_USER=${DJANGO_DATABASE_USER}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  mock-server:
    image: python:3.11.9-slim
    container_name: mock-server
    working_dir: /mock
    command: python3 -m http.server 8080
    ports:
      - "8080:8080"
    volumes:
      - ./mock-pms-api:/mock
    restart: unless-stopped

volumes:
  postgres_data: